# Generated by Django 5.2 on 2025-04-16 00:27

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.Manager()),
            ],
        ),
    ]
